# Använd Red Hat UBI nginx image
FROM registry.access.redhat.com/ubi10/nginx-126:10.0

# Kopiera index.html till nginx html-mapp
COPY index.html /usr/share/nginx/html/index.html

# Kopiera nginx.conf till rätt plats
#COPY nginx.conf /etc/nginx/nginx.conf

# Exponera port 80-> container port
EXPOSE 80

# Starta nginx i förgrund
CMD ["nginx", "-g", "daemon off;"]