# Använd Red Hat UBI nginx image- Bas image används med installerad Openshift(Kubernetes)- FUNGERAR INTE LOKALT
#FROM registry.access.redhat.com/ubi10/nginx-126:10.0

# Testa lokalt med Podman + Windows, Ingen Openshift: Bas image nginx:alpine
FROM nginx:alpine

# Kopiera index.html och lägger i följande path- Används lokalt och med Openshift!
COPY index.html /opt/app-root/src/index.html

# Kopiera nginx.conf fil och lägger i följande path- används med installerad Openshift(Kubernetes)- FUNGERAR INTE LOKALT
# Skapat lokal-nginx-conf som använder inernal proxy pass som konfigurear till backend:http://host.containers.internal:8080;->lokal konf till backend

#COPY local-nginx.conf /etc/nginx/nginx.conf->med Openshift
COPY local-nginx.conf /etc/nginx/conf.d/default.conf

# Internt port 8080->web port 8081
EXPOSE 8080

# Starta nginx webserver
CMD ["nginx", "-g", "daemon off;"]