#automatisera containers i pipeline
# måste ha github container registry för att pulla image



name: Build and Push Container

#trigger feature branch
on:
  push:
    branches: 
      - feature/* 
      
  pull_request:
    branches:
      - main  

#bygga frontend image
jobs:
  
  build-frontend:
    runs-on: ubuntu-latest

    permission:
      contents: read
      packages: write

    steps:
   #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.almafrank }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger frontend image med container
      - name: Build frontend image
        run: |
          docker build \
          -f frontend/Containerfile\
          -t ghcr.io/almafrank/localhost/frontend-guestbook:latest\
          frontend-guestbook
          
      

      - name: Push frontend image
        run: |
          docker push ghcr.io/almafrank/localhost/frontend-guestbook:latest\
          frontend-guestbook

  build-backend:
    needs: build-frontend
    build-backend:
    runs-on: ubuntu-latest
    steps:

    #Kollar repot
      - name: Checkout repo
        uses: actions/checkout@v4

    # Logga in på Github för att pusha och pulla images i Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN2026 }}
    
    #Bygger backend image med container
      - name: Build backend image
        run: |
          docker build \
          -f backend/Containerfile\
          -t ghcr.io/almafrank/localhost/backend-guestbook:latest\
          backend-guestbook

      - name: Push backend image
        run: |
          docker push ghcr.io/almafrank/localhost/backend-guestbook:latest\
          backend-guestbook
          
          
          
      
     


  

    
    



    











